import React, { ReactNode } from 'react';
import { GetContentTypes } from './ReactTooltip';

export type ReactTooltipProps = {
  uuid: string;
  children: ReactNode;
  place: string;
  type: string;
  effect: string;
  offset: object;
  padding: string;
  multiline: boolean;
  border: boolean;
  textColor: string;
  backgroundColor: string;
  borderColor: string;
  arrowColor: string;
  insecure: boolean;
  class: string;
  className: string;
  id: string;
  html: boolean;
  delayHide: number;
  delayUpdate: number;
  delayShow: number;
  event: string;
  eventOff: string;
  isCapture: boolean;
  globalEventOff: string;
  getContent: GetContentTypes | GetContentTypes[];
  afterShow(e: React.MouseEvent<HTMLElement, MouseEvent>);
  afterHide(e: React.MouseEvent<HTMLElement, MouseEvent>);
  overridePosition(a, b, c, d, e, f, g, h);
  disable: boolean;
  scrollHide: boolean;
  resizeHide: boolean;
  wrapper: string;
  bodyMode: boolean;
  possibleCustomEvents: string;
  possibleCustomEventsOff: string;
  clickable: boolean;
};
